### ISSUE TITLE
Could not be verified for use in IceCat

### ISSUE THREAD

**Issue by Marek33** [muslayev/icecat-win64#34]
Multiple extensions, now says this: **could not be verified for use in IceCat. Proceed with caution.** Even the **IceDownload** _(in Iceweasel as well)_, expect the LibreJS/USPS compatibility and Reveal hidden HTML, which are the only ones, which doesn't have it.

Plus, the **disable-polymer-YouTube** should be removed anyway, since it doesn't bring back the old YouTube. Only the **Old YouTube** extensions help.

**Comment by mimecry** [comment]
would be great if we can remove some of these redundant addons as well

**Comment by muslayev** [comment]
Because some extensions (part of icecat) have not been signed (except two ones), i added settings:
pref("xpinstall.signatures.required", false);
pref("xpinstall.whitelist.required", false);
pref("extensions.langpacks.signatures.required", false);
pref("extensions.autoDisableScopes", 2);

Also, i did changes for IceDownload (fixed issue when extension could not determine if new version is released), and it is not signed yet.

>would be great if we can remove some of these redundant addons as well

Hope icecat devs will review all existing extensions, and will remove outdated.

**Comment by Marek33** [comment]
That would be great, since stuff like the disable-polymer-YouTube, is absolutely not needed, and with the uBlock Origin, these two are also not needed: **Searxes' Third-party Request Blocker** and **GNU LibreJS**. Plus, I don't see any reason, to have the **Workarounds for nonfree JS**, which I doubt that most of the people ever need to use.

Yes, I hope that they will do that as well, and especially, that they will remove, most of the useless, extensions. Or at least, give us an option, to remove them.

**Comment by Marek33** [comment]
Thank you, very much for releasing the new version, and the and the Icecat developers for making that browser! Now there are no unnecessary add-ons, expect the IceDownload, (which is useful) and it no longer says the *Could not be verified for use in IceCat*. The only thing which needs to be done (by Mozilla thou) is to change the visible Fonts to the other ones, by the normal Firefox releases (if privacy.resist.fingerprinting is enabled).

_Though, I still don't get, why the Icecat, doesn't hide that I use 64bit Win7, and not 32bit Win10, which it probably should._
